/** Copy for /terms and /privacy — keep aligned with actual product behavior. */

export const LEGAL_LAST_UPDATED = '21 May 2026'

export const TERMS_SECTIONS = [
  {
    id: 'agreement',
    title: '1. Agreement',
    paragraphs: [
      'These Terms of Service ("Terms") govern your access to and use of Heartimate ("Heartimate", "we", "us", or "the Service") — a web application for fictional AI character roleplay, including optional adult (18+) content.',
      'By creating an account or using the Service, you agree to these Terms. If you do not agree, do not use Heartimate.',
    ],
  },
  {
    id: 'adults-only',
    title: '2. Adults only (18+)',
    paragraphs: [
      'Heartimate is intended only for people who are at least 18 years old (or the age of majority where you live, if higher).',
      'You may not use the Service if you are under 18. During onboarding you confirm that you are 18 or older. We may suspend accounts that we reasonably believe belong to minors.',
      'The Service may include explicit sexual or mature fictional content when characters or chats are marked as NSFW. That content is fiction between consenting adults, not real-world instruction.',
    ],
  },
  {
    id: 'account',
    title: '3. Accounts and security',
    paragraphs: [
      'You sign in through our authentication provider (Clerk). You are responsible for keeping your login credentials secure and for activity under your account.',
      'Provide accurate information (such as display name) and notify us if you suspect unauthorized access. We are not liable for losses caused by someone else using your account with your credentials.',
    ],
  },
  {
    id: 'your-content',
    title: '4. Your content and characters',
    paragraphs: [
      'You may create characters, personas, and chat messages ("Your Content"). You retain ownership of Your Content. You grant Heartimate a non-exclusive, worldwide license to host, store, process, and display Your Content only as needed to operate the Service (including sending message text to our AI provider to generate replies).',
      'You are responsible for Your Content. Do not upload or publish content that is illegal, infringes others\' rights, or violates these Terms.',
    ],
    list: [
      'No sexual content involving minors or characters portrayed as minors.',
      'No promotion of real-world illegal violence or non-consensual harm.',
      'No harassment, doxxing, spam, or malware.',
      'No impersonation of real people in a deceptive or harmful way.',
    ],
  },
  {
    id: 'public-characters',
    title: '5. Public characters and community',
    paragraphs: [
      'You may mark characters as public so other users can discover and chat with them. Public content must follow the same rules as Your Content.',
      'Other users may report characters they believe violate our rules. We may remove or restrict content and accounts at our discretion, without prior notice.',
    ],
  },
  {
    id: 'ai',
    title: '6. AI-generated responses',
    paragraphs: [
      'Replies are generated by third-party language models (via OpenRouter). AI output can be wrong, inconsistent, or offensive. It is fictional roleplay, not professional advice (medical, legal, financial, or otherwise).',
      'Do not rely on the Service for real-world decisions. You use AI responses at your own risk.',
    ],
  },
  {
    id: 'acceptable-use',
    title: '7. Acceptable use',
    paragraphs: [
      'You agree not to misuse the Service, including attempting to bypass rate limits, scrape or overload our systems, reverse engineer the app except where law allows, or use automated bots without permission.',
      'We may apply daily message limits, rate limits, and maintenance modes (including temporarily disabling chat) to protect the Service and control costs.',
    ],
  },
  {
    id: 'beta',
    title: '8. Beta service',
    paragraphs: [
      'Heartimate may be offered as a beta. Features, limits, and availability can change at any time. The Service is provided "as is" without warranties of uninterrupted or error-free operation.',
    ],
  },
  {
    id: 'termination',
    title: '9. Suspension and termination',
    paragraphs: [
      'You may stop using the Service at any time. We may suspend or terminate your access if you breach these Terms, if required by law, or to protect users and the platform.',
      'Upon termination, your right to use the Service ends. Some data may be retained as described in our Privacy Policy.',
    ],
  },
  {
    id: 'disclaimer',
    title: '10. Disclaimers and liability',
    paragraphs: [
      'To the fullest extent permitted by law, Heartimate and its operators disclaim all warranties, express or implied. We are not liable for indirect, incidental, special, or consequential damages, or for loss of data, profits, or goodwill arising from your use of the Service.',
      'Our total liability for any claim relating to the Service is limited to the greater of (a) amounts you paid us in the twelve months before the claim, or (b) one hundred US dollars (USD $100), if you have not paid us.',
      'Some jurisdictions do not allow certain limitations; in those cases, our liability is limited to the maximum permitted by law.',
    ],
  },
  {
    id: 'changes',
    title: '11. Changes to these Terms',
    paragraphs: [
      'We may update these Terms from time to time. We will post the revised version on this page and update the "Last updated" date. Continued use after changes means you accept the updated Terms.',
    ],
  },
  {
    id: 'contact',
    title: '12. Contact',
    paragraphs: [
      'Questions about these Terms: use the support or contact channel published on the Heartimate website or app when available.',
    ],
  },
] as const

export const PRIVACY_SECTIONS = [
  {
    id: 'overview',
    title: '1. Overview',
    paragraphs: [
      'This Privacy Policy explains how Heartimate collects, uses, and shares information when you use our website and app.',
      'We process data to provide AI roleplay, authentication, storage of your chats and characters, and security. We do not sell your personal information.',
    ],
  },
  {
    id: 'collect',
    title: '2. Information we collect',
    paragraphs: [
      'The information we collect depends on how you use the Service.',
    ],
    list: [
      'Account data: identifiers and profile fields tied to your sign-in (e.g. user id, email if you provide it, display name you set in Heartimate).',
      'App profile: display name, optional bio, avatar URL, kink preferences, adult confirmation timestamp, and similar fields stored on our systems.',
      'User content: characters, personas, chat messages, likes, reports, and related metadata you create.',
      'Usage and technical data: IP address, browser or device type, request logs, crash and error reports, and events about how you use the app (for example which pages you visit or when you start a chat).',
      'Cookies and local storage: session and preference data needed for sign-in and the app to function.',
    ],
  },
  {
    id: 'use',
    title: '3. How we use information',
    paragraphs: [
      'We use information to:',
    ],
    list: [
      'Authenticate you and operate your account.',
      'Store and sync your chats, characters, and personas.',
      'Send your messages and character context to AI providers to generate replies.',
      'Enforce rate limits, prevent abuse, and keep the Service secure.',
      'Improve reliability, fix bugs, and understand which parts of the app people use.',
      'Respond to reports and comply with legal obligations.',
    ],
  },
  {
    id: 'sharing',
    title: '4. When we share information',
    paragraphs: [
      'We share data with service providers who help us run Heartimate, under contracts that require them to protect your information:',
      'We may also disclose information if required by law, to protect rights and safety, or in connection with a merger or sale of the business (with notice where required).',
    ],
    list: [
      'Authentication and session services — sign-in and account access.',
      'Hosting and data storage — database, file storage (e.g. avatars), and your app data.',
      'AI providers — processing chat content to produce responses. Message content is sent to generate replies; do not include sensitive real-world data you do not want processed by third parties.',
      'Application hosting — serving the website and app, including server and error logs.',
    ],
  },
  {
    id: 'retention',
    title: '5. Retention',
    paragraphs: [
      'We keep your account and content while your account is active. If you delete content or your account, we delete or anonymize data within a reasonable period, except where we must retain it for legal, security, or backup reasons.',
      'Server logs and rate-limit records may be retained for a limited time (e.g. rolling windows for abuse prevention) and then purged.',
    ],
  },
  {
    id: 'security',
    title: '6. Security',
    paragraphs: [
      'We use industry-standard measures such as HTTPS, access controls, and row-level security on user data. No system is perfectly secure; use a strong password and protect your login.',
    ],
  },
  {
    id: 'rights',
    title: '7. Your choices and rights',
    paragraphs: [
      'You can update profile fields in the app, delete messages or chats where the product allows, and sign out at any time.',
      'Depending on where you live, you may have rights to access, correct, delete, or export personal data, or to object to certain processing. Contact us through the support channel on the Service to make a request. We may need to verify your identity.',
    ],
  },
  {
    id: 'children',
    title: '8. Children',
    paragraphs: [
      'Heartimate is not for anyone under 18. We do not knowingly collect data from minors. If you believe a minor has used the Service, contact us so we can take appropriate action.',
    ],
  },
  {
    id: 'international',
    title: '9. International users',
    paragraphs: [
      'Your data may be processed in the United States and other countries where our providers operate. By using the Service, you understand that laws in those locations may differ from yours.',
    ],
  },
  {
    id: 'changes-privacy',
    title: '10. Changes to this policy',
    paragraphs: [
      'We may update this Privacy Policy. We will post changes on this page and update the "Last updated" date. Material changes may be communicated in the app where appropriate.',
    ],
  },
  {
    id: 'contact-privacy',
    title: '11. Contact',
    paragraphs: [
      'Privacy questions: use the support or contact channel published on the Heartimate website or app when available.',
    ],
  },
] as const
