export const AVAILABLE_TAGS = [
  'Romance',
  'Dark Fantasy',
  'Sci-Fi',
  'Supernatural',
  'Enemies to Lovers',
  'Forbidden Love',
  'Dominant',
  'Submissive',
  'Soft Dom',
  'Yandere',
  'Tsundere',
  'Slow Burn',
  'Age Gap',
  'Childhood Friends',
  'Monster/Non-human',
  'Historical',
  'Horror',
  'Possessive',
  'Mentor/Student',
  'Obsessive',
  'Hurt/Comfort',
  'Sweet',
  'Protective',
  'Villain',
] as const
